name: CI

on:
  push:
    branches: [ "main" ] # Trigger on pushes to the main branch
  pull_request:
    branches: [ "main" ] # Trigger on pull requests to the main branch
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  tag-on-merge:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Use GitHub Tag Bump Action to handle version tagging
      - name: Bump Version and Tag
        uses: anothrnick/github-tag-action@v1.41.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          bump_type: patch # Bumps the patch version (e.g., v1.0.0 -> v1.0.1)

      - name: Push Tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push --tags
